; Generado por «python herramientas_idioma.py instalador» a partir de
; empaquetado/idiomas/*.json: no editar a mano (r136).

[Messages]
es.WelcomeLabel2=Se instalará [name/ver] en este equipo.%n%nDurante la instalación se descargarán de sus sitios oficiales Python, los componentes de Python y las fuentes tipográficas (unos {#ComponentesMB} MB): hace falta conexión a Internet.%n%nSe recomienda cerrar AventyaPDF antes de continuar.
en.WelcomeLabel2=This will install [name/ver] on your computer.%n%nDuring installation, Python, the Python components and the fonts (about {#ComponentesMB} MB) will be downloaded from their official sites: an Internet connection is required.%n%nIt is recommended that you close AventyaPDF before continuing.
fr.WelcomeLabel2=[name/ver] va être installé sur cet ordinateur.%n%nPendant l'installation, Python, les composants Python et les polices de caractères (environ {#ComponentesMB} Mo) seront téléchargés depuis leurs sites officiels : une connexion Internet est nécessaire.%n%nIl est recommandé de fermer AventyaPDF avant de continuer.
it.WelcomeLabel2=Verrà installato [name/ver] in questo computer.%n%nDurante l'installazione verranno scaricati dai rispettivi siti ufficiali Python, i componenti di Python e i tipi di carattere (circa {#ComponentesMB} MB): è necessaria una connessione a Internet.%n%nSi consiglia di chiudere AventyaPDF prima di continuare.
ca.WelcomeLabel2=S'instal·larà [name/ver] en aquest ordinador.%n%nDurant la instal·lació es baixaran dels seus llocs oficials Python, els components de Python i els tipus de lletra (uns {#ComponentesMB} MB): cal connexió a Internet.%n%nEs recomana tancar AventyaPDF abans de continuar.
gl.WelcomeLabel2=Vaise instalar [name/ver] neste equipo.%n%nDurante a instalación descargaranse dos seus sitios oficiais Python, os compoñentes de Python e as fontes tipográficas (uns {#ComponentesMB} MB): cómpre ter conexión a Internet.%n%nRecoméndase pechar AventyaPDF antes de continuar.
eu.WelcomeLabel2=[name/ver] ordenagailu honetan instalatuko da.%n%nInstalazioan zehar, Python, Python-en osagaiak eta letra-tipoak deskargatuko dira haien webgune ofizialetatik ({#ComponentesMB} MB inguru): Interneteko konexioa behar da.%n%nAventyaPDF ixtea gomendatzen da jarraitu aurretik.

[CustomMessages]
es.TareaEscritorio=Crear un acceso directo en el escritorio
es.GrupoAccesos=Accesos directos:
es.PreparandoArranque=Preparando AventyaPDF para el primer arranque…
es.AbrirApp=Abrir %1
es.MenuConfianza=Para que el submenú «AventyaPDF» aparezca en el menú del botón derecho de Windows 11, Windows tiene que confiar en el certificado de AventyaPDF.%n%nA continuación Windows pedirá permiso de administrador (solo esta vez en este equipo).
es.MenuSinPermiso=No se ha dado el permiso de administrador.%n%nSin él, el submenú «AventyaPDF» del botón derecho quedará en «Mostrar más opciones». ¿Volver a pedirlo?%n%n(También se puede hacer más tarde desde AventyaPDF: Ayuda › Reparar el menú contextual del Explorador.)
es.MenuFallo=No se pudo añadir el submenú «AventyaPDF» al menú principal de Windows 11 (sigue en «Mostrar más opciones»). Detalle en:
es.CertQuitar=Para quitar de este equipo el certificado del menú del botón derecho de AventyaPDF, Windows pedirá permiso de administrador.
es.CertNoQuitado=No se ha quitado el certificado de AventyaPDF de «Personas de confianza» del equipo (no se dio el permiso de administrador).%n%nSe puede quitar a mano: «Administrar certificados de equipo» (certlm.msc) › Personas de confianza › Certificados › «Aventya Asesoria Integral SL».
es.MenuFirmar=Firmar digitalmente
es.MenuCombinar=Combinar en un PDF
es.MenuConvertir=Convertir a PDF
es.TipoDocumento=Documento PDF
es.DescripcionApp=Visor y editor de PDF con firma digital y OCR
en.TareaEscritorio=Create a desktop shortcut
en.GrupoAccesos=Shortcuts:
en.PreparandoArranque=Preparing AventyaPDF for first launch…
en.AbrirApp=Open %1
en.MenuConfianza=For the “AventyaPDF” submenu to appear in the Windows 11 right-click menu, Windows has to trust the AventyaPDF certificate.%n%nWindows will now ask for administrator permission (only this once on this computer).
en.MenuSinPermiso=Administrator permission wasn't granted.%n%nWithout it, the “AventyaPDF” right-click submenu will stay under “Show more options”. Ask again?%n%n(You can also do this later from AventyaPDF: Help › Repair the File Explorer context menu.)
en.MenuFallo=Couldn't add the “AventyaPDF” submenu to the Windows 11 main menu (it's still under “Show more options”). Details in:
en.CertQuitar=To remove the AventyaPDF right-click menu certificate from this computer, Windows will ask for administrator permission.
en.CertNoQuitado=The AventyaPDF certificate wasn't removed from the computer's “Trusted People” store (administrator permission wasn't granted).%n%nYou can remove it manually: “Manage computer certificates” (certlm.msc) › Trusted People › Certificates › “Aventya Asesoria Integral SL”.
en.MenuFirmar=Sign digitally
en.MenuCombinar=Combine into one PDF
en.MenuConvertir=Convert to PDF
en.TipoDocumento=PDF document
en.DescripcionApp=PDF viewer and editor with digital signature and OCR
fr.TareaEscritorio=Créer un raccourci sur le Bureau
fr.GrupoAccesos=Raccourcis :
fr.PreparandoArranque=Préparation d'AventyaPDF pour le premier démarrage…
fr.AbrirApp=Ouvrir %1
fr.MenuConfianza=Pour que le sous-menu « AventyaPDF » apparaisse dans le menu du clic droit de Windows 11, Windows doit faire confiance au certificat d'AventyaPDF.%n%nWindows va maintenant demander l'autorisation d'administrateur (une seule fois sur cet ordinateur).
fr.MenuSinPermiso=L'autorisation d'administrateur n'a pas été accordée.%n%nSans elle, le sous-menu « AventyaPDF » du clic droit restera dans « Afficher plus d'options ». La demander à nouveau ?%n%n(Vous pouvez aussi le faire plus tard depuis AventyaPDF : Aide › Réparer le menu contextuel de l'Explorateur.)
fr.MenuFallo=Impossible d'ajouter le sous-menu « AventyaPDF » au menu principal de Windows 11 (il reste dans « Afficher plus d'options »). Détails dans :
fr.CertQuitar=Pour supprimer de cet ordinateur le certificat du menu du clic droit d'AventyaPDF, Windows va demander l'autorisation d'administrateur.
fr.CertNoQuitado=Le certificat d'AventyaPDF n'a pas été supprimé des « Personnes autorisées » de l'ordinateur (l'autorisation d'administrateur n'a pas été accordée).%n%nVous pouvez le supprimer manuellement : « Gérer les certificats de l'ordinateur » (certlm.msc) › Personnes autorisées › Certificats › « Aventya Asesoria Integral SL ».
fr.MenuFirmar=Signer numériquement
fr.MenuCombinar=Combiner en un PDF
fr.MenuConvertir=Convertir en PDF
fr.TipoDocumento=Document PDF
fr.DescripcionApp=Visionneuse et éditeur PDF avec signature numérique et OCR
it.TareaEscritorio=Crea un collegamento sul desktop
it.GrupoAccesos=Collegamenti:
it.PreparandoArranque=Preparazione di AventyaPDF per il primo avvio…
it.AbrirApp=Apri %1
it.MenuConfianza=Perché il sottomenu «AventyaPDF» compaia nel menu del clic destro di Windows 11, Windows deve considerare attendibile il certificato di AventyaPDF.%n%nOra Windows chiederà l'autorizzazione di amministratore (solo questa volta in questo computer).
it.MenuSinPermiso=L'autorizzazione di amministratore non è stata concessa.%n%nSenza di essa, il sottomenu «AventyaPDF» del clic destro rimarrà in «Mostra altre opzioni». Richiederla di nuovo?%n%n(È possibile farlo anche in seguito da AventyaPDF: Guida › Ripara il menu contestuale di Esplora file.)
it.MenuFallo=Impossibile aggiungere il sottomenu «AventyaPDF» al menu principale di Windows 11 (rimane in «Mostra altre opzioni»). Dettagli in:
it.CertQuitar=Per rimuovere da questo computer il certificato del menu del clic destro di AventyaPDF, Windows chiederà l'autorizzazione di amministratore.
it.CertNoQuitado=Il certificato di AventyaPDF non è stato rimosso da «Persone attendibili» del computer (l'autorizzazione di amministratore non è stata concessa).%n%nÈ possibile rimuoverlo manualmente: «Gestisci certificati computer» (certlm.msc) › Persone attendibili › Certificati › «Aventya Asesoria Integral SL».
it.MenuFirmar=Firma digitalmente
it.MenuCombinar=Combina in un PDF
it.MenuConvertir=Converti in PDF
it.TipoDocumento=Documento PDF
it.DescripcionApp=Visualizzatore ed editor PDF con firma digitale e OCR
ca.TareaEscritorio=Crea una drecera a l'escriptori
ca.GrupoAccesos=Dreceres:
ca.PreparandoArranque=S'està preparant AventyaPDF per a la primera execució…
ca.AbrirApp=Obre %1
ca.MenuConfianza=Perquè el submenú «AventyaPDF» aparegui al menú del botó dret de Windows 11, Windows ha de confiar en el certificat d'AventyaPDF.%n%nA continuació Windows demanarà permís d'administrador (només aquesta vegada en aquest ordinador).
ca.MenuSinPermiso=No s'ha donat el permís d'administrador.%n%nSense aquest permís, el submenú «AventyaPDF» del botó dret quedarà a «Mostra més opcions». Voleu tornar-lo a demanar?%n%n(També es pot fer més endavant des d'AventyaPDF: Ajuda › Repara el menú contextual de l'Explorador de fitxers.)
ca.MenuFallo=No s'ha pogut afegir el submenú «AventyaPDF» al menú principal de Windows 11 (continua a «Mostra més opcions»). Detall a:
ca.CertQuitar=Per treure d'aquest ordinador el certificat del menú del botó dret d'AventyaPDF, Windows demanarà permís d'administrador.
ca.CertNoQuitado=No s'ha tret el certificat d'AventyaPDF de «Persones de confiança» de l'ordinador (no s'ha donat el permís d'administrador).%n%nEs pot treure manualment: «Administra els certificats de l'ordinador» (certlm.msc) › Persones de confiança › Certificats › «Aventya Asesoria Integral SL».
ca.MenuFirmar=Signa digitalment
ca.MenuCombinar=Combina en un PDF
ca.MenuConvertir=Converteix a PDF
ca.TipoDocumento=Document PDF
ca.DescripcionApp=Visualitzador i editor de PDF amb signatura digital i OCR
gl.TareaEscritorio=Crear un atallo no escritorio
gl.GrupoAccesos=Atallos:
gl.PreparandoArranque=Preparando AventyaPDF para o primeiro inicio…
gl.AbrirApp=Abrir %1
gl.MenuConfianza=Para que o submenú «AventyaPDF» apareza no menú do botón dereito de Windows 11, Windows ten que confiar no certificado de AventyaPDF.%n%nA continuación Windows pedirá permiso de administrador (só esta vez neste equipo).
gl.MenuSinPermiso=Non se deu o permiso de administrador.%n%nSen el, o submenú «AventyaPDF» do botón dereito quedará en «Mostrar máis opcións». Queres volver pedilo?%n%n(Tamén se pode facer máis tarde desde AventyaPDF: Axuda › Reparar o menú contextual do Explorador de ficheiros.)
gl.MenuFallo=Non se puido engadir o submenú «AventyaPDF» ao menú principal de Windows 11 (segue en «Mostrar máis opcións»). Detalle en:
gl.CertQuitar=Para quitar deste equipo o certificado do menú do botón dereito de AventyaPDF, Windows pedirá permiso de administrador.
gl.CertNoQuitado=Non se quitou o certificado de AventyaPDF de «Persoas de confianza» do equipo (non se deu o permiso de administrador).%n%nPódese quitar manualmente: «Xestionar certificados do equipo» (certlm.msc) › Persoas de confianza › Certificados › «Aventya Asesoria Integral SL».
gl.MenuFirmar=Asinar dixitalmente
gl.MenuCombinar=Combinar nun PDF
gl.MenuConvertir=Converter a PDF
gl.TipoDocumento=Documento PDF
gl.DescripcionApp=Visor e editor de PDF con sinatura dixital e OCR
eu.TareaEscritorio=Sortu lasterbide bat mahaigainean
eu.GrupoAccesos=Lasterbideak:
eu.PreparandoArranque=AventyaPDF lehen abiaraztekoa prestatzen…
eu.AbrirApp=Ireki %1
eu.MenuConfianza=«AventyaPDF» azpimenua Windows 11ko eskuineko botoiaren menuan ager dadin, Windows-ek AventyaPDF-ren ziurtagiriaz fidatu behar du.%n%nJarraian, Windows-ek administratzaile-baimena eskatuko du (behin bakarrik ordenagailu honetan).
eu.MenuSinPermiso=Ez da administratzaile-baimena eman.%n%nBaimen hori gabe, eskuineko botoiaren «AventyaPDF» azpimenua «Erakutsi aukera gehiago» barruan geratuko da. Berriro eskatu?%n%n(Geroago ere egin daiteke AventyaPDF-tik: Laguntza › Konpondu Fitxategi-arakatzailearen laster-menua.)
eu.MenuFallo=Ezin izan da «AventyaPDF» azpimenua Windows 11ko menu nagusian gehitu («Erakutsi aukera gehiago» barruan dago oraindik). Xehetasunak hemen:
eu.CertQuitar=AventyaPDF-ren eskuineko botoiaren menuko ziurtagiria ordenagailu honetatik kentzeko, Windows-ek administratzaile-baimena eskatuko du.
eu.CertNoQuitado=Ez da AventyaPDF-ren ziurtagiria kendu ordenagailuko «Pertsona fidagarriak» biltegitik (ez da administratzaile-baimena eman).%n%nEskuz ken daiteke: «Kudeatu ordenagailuaren ziurtagiriak» (certlm.msc) › Pertsona fidagarriak › Ziurtagiriak › «Aventya Asesoria Integral SL».
eu.MenuFirmar=Sinatu digitalki
eu.MenuCombinar=Konbinatu PDF bakarrean
eu.MenuConvertir=Bihurtu PDF
eu.TipoDocumento=PDF dokumentua
eu.DescripcionApp=PDF ikustailea eta editorea, sinadura digitalarekin eta OCRarekin
