; Generado por «python herramientas_idioma.py instalador» a partir de
; empaquetado/idiomas/*.json y de las diapositivas de presentacion.py
; (traducidas en idiomas/*.json): no editar a mano (r136, r138).

#define NumDiapositivas 14

[Messages]
es.WelcomeLabel2=Se instalará [name/ver] en este equipo.%n%nDurante la instalación se descargarán de sus sitios oficiales Python, los componentes de Python y las fuentes tipográficas (unos {#ComponentesMB} MB): hace falta conexión a Internet.%n%nSe recomienda cerrar AventyaPDF antes de continuar.
en.WelcomeLabel2=This will install [name/ver] on your computer.%n%nDuring installation, Python, the Python components and the fonts (about {#ComponentesMB} MB) will be downloaded from their official sites: an Internet connection is required.%n%nIt is recommended that you close AventyaPDF before continuing.
fr.WelcomeLabel2=[name/ver] va être installé sur cet ordinateur.%n%nPendant l'installation, Python, les composants Python et les polices de caractères (environ {#ComponentesMB} Mo) seront téléchargés depuis leurs sites officiels : une connexion Internet est nécessaire.%n%nIl est recommandé de fermer AventyaPDF avant de continuer.
it.WelcomeLabel2=Verrà installato [name/ver] in questo computer.%n%nDurante l'installazione verranno scaricati dai rispettivi siti ufficiali Python, i componenti di Python e i tipi di carattere (circa {#ComponentesMB} MB): è necessaria una connessione a Internet.%n%nSi consiglia di chiudere AventyaPDF prima di continuare.
ca.WelcomeLabel2=S'instal·larà [name/ver] en aquest ordinador.%n%nDurant la instal·lació es baixaran dels seus llocs oficials Python, els components de Python i els tipus de lletra (uns {#ComponentesMB} MB): cal connexió a Internet.%n%nEs recomana tancar AventyaPDF abans de continuar.
gl.WelcomeLabel2=Vaise instalar [name/ver] neste equipo.%n%nDurante a instalación descargaranse dos seus sitios oficiais Python, os compoñentes de Python e as fontes tipográficas (uns {#ComponentesMB} MB): cómpre ter conexión a Internet.%n%nRecoméndase pechar AventyaPDF antes de continuar.
eu.WelcomeLabel2=[name/ver] ordenagailu honetan instalatuko da.%n%nInstalazioan zehar, Python, Python-en osagaiak eta letra-tipoak deskargatuko dira haien webgune ofizialetatik ({#ComponentesMB} MB inguru): Interneteko konexioa behar da.%n%nAventyaPDF ixtea gomendatzen da jarraitu aurretik.

[CustomMessages]
es.TareaEscritorio=Crear un acceso directo en el escritorio
es.GrupoAccesos=Accesos directos:
es.PreparandoArranque=Preparando AventyaPDF para el primer arranque…
es.AbrirApp=Abrir %1
es.MenuConfianza=Para que el submenú «AventyaPDF» aparezca en el menú del botón derecho de Windows 11, Windows tiene que confiar en el certificado de AventyaPDF.%n%nA continuación Windows pedirá permiso de administrador (solo esta vez en este equipo).
es.MenuSinPermiso=No se ha dado el permiso de administrador.%n%nSin él, el submenú «AventyaPDF» del botón derecho quedará en «Mostrar más opciones». ¿Volver a pedirlo?%n%n(También se puede hacer más tarde desde AventyaPDF: Ayuda › Reparar el menú contextual del Explorador.)
es.MenuFallo=No se pudo añadir el submenú «AventyaPDF» al menú principal de Windows 11 (sigue en «Mostrar más opciones»). Detalle en:
es.CertQuitar=Para quitar de este equipo el certificado del menú del botón derecho de AventyaPDF, Windows pedirá permiso de administrador.
es.CertNoQuitado=No se ha quitado el certificado de AventyaPDF de «Personas de confianza» del equipo (no se dio el permiso de administrador).%n%nSe puede quitar a mano: «Administrar certificados de equipo» (certlm.msc) › Personas de confianza › Certificados › «Aventya Asesoria Integral SL».
es.MenuFirmar=Firmar digitalmente
es.MenuCombinar=Combinar en un PDF
es.MenuConvertir=Convertir a PDF
es.TipoDocumento=Documento PDF
es.DescripcionApp=Visor y editor de PDF con firma digital y OCR
en.TareaEscritorio=Create a desktop shortcut
en.GrupoAccesos=Shortcuts:
en.PreparandoArranque=Preparing AventyaPDF for first launch…
en.AbrirApp=Open %1
en.MenuConfianza=For the “AventyaPDF” submenu to appear in the Windows 11 right-click menu, Windows has to trust the AventyaPDF certificate.%n%nWindows will now ask for administrator permission (only this once on this computer).
en.MenuSinPermiso=Administrator permission wasn't granted.%n%nWithout it, the “AventyaPDF” right-click submenu will stay under “Show more options”. Ask again?%n%n(You can also do this later from AventyaPDF: Help › Repair the File Explorer context menu.)
en.MenuFallo=Couldn't add the “AventyaPDF” submenu to the Windows 11 main menu (it's still under “Show more options”). Details in:
en.CertQuitar=To remove the AventyaPDF right-click menu certificate from this computer, Windows will ask for administrator permission.
en.CertNoQuitado=The AventyaPDF certificate wasn't removed from the computer's “Trusted People” store (administrator permission wasn't granted).%n%nYou can remove it manually: “Manage computer certificates” (certlm.msc) › Trusted People › Certificates › “Aventya Asesoria Integral SL”.
en.MenuFirmar=Sign digitally
en.MenuCombinar=Combine into one PDF
en.MenuConvertir=Convert to PDF
en.TipoDocumento=PDF document
en.DescripcionApp=PDF viewer and editor with digital signature and OCR
fr.TareaEscritorio=Créer un raccourci sur le Bureau
fr.GrupoAccesos=Raccourcis :
fr.PreparandoArranque=Préparation d'AventyaPDF pour le premier démarrage…
fr.AbrirApp=Ouvrir %1
fr.MenuConfianza=Pour que le sous-menu « AventyaPDF » apparaisse dans le menu du clic droit de Windows 11, Windows doit faire confiance au certificat d'AventyaPDF.%n%nWindows va maintenant demander l'autorisation d'administrateur (une seule fois sur cet ordinateur).
fr.MenuSinPermiso=L'autorisation d'administrateur n'a pas été accordée.%n%nSans elle, le sous-menu « AventyaPDF » du clic droit restera dans « Afficher plus d'options ». La demander à nouveau ?%n%n(Vous pouvez aussi le faire plus tard depuis AventyaPDF : Aide › Réparer le menu contextuel de l'Explorateur.)
fr.MenuFallo=Impossible d'ajouter le sous-menu « AventyaPDF » au menu principal de Windows 11 (il reste dans « Afficher plus d'options »). Détails dans :
fr.CertQuitar=Pour supprimer de cet ordinateur le certificat du menu du clic droit d'AventyaPDF, Windows va demander l'autorisation d'administrateur.
fr.CertNoQuitado=Le certificat d'AventyaPDF n'a pas été supprimé des « Personnes autorisées » de l'ordinateur (l'autorisation d'administrateur n'a pas été accordée).%n%nVous pouvez le supprimer manuellement : « Gérer les certificats de l'ordinateur » (certlm.msc) › Personnes autorisées › Certificats › « Aventya Asesoria Integral SL ».
fr.MenuFirmar=Signer numériquement
fr.MenuCombinar=Combiner en un PDF
fr.MenuConvertir=Convertir en PDF
fr.TipoDocumento=Document PDF
fr.DescripcionApp=Visionneuse et éditeur PDF avec signature numérique et OCR
it.TareaEscritorio=Crea un collegamento sul desktop
it.GrupoAccesos=Collegamenti:
it.PreparandoArranque=Preparazione di AventyaPDF per il primo avvio…
it.AbrirApp=Apri %1
it.MenuConfianza=Perché il sottomenu «AventyaPDF» compaia nel menu del clic destro di Windows 11, Windows deve considerare attendibile il certificato di AventyaPDF.%n%nOra Windows chiederà l'autorizzazione di amministratore (solo questa volta in questo computer).
it.MenuSinPermiso=L'autorizzazione di amministratore non è stata concessa.%n%nSenza di essa, il sottomenu «AventyaPDF» del clic destro rimarrà in «Mostra altre opzioni». Richiederla di nuovo?%n%n(È possibile farlo anche in seguito da AventyaPDF: Guida › Ripara il menu contestuale di Esplora file.)
it.MenuFallo=Impossibile aggiungere il sottomenu «AventyaPDF» al menu principale di Windows 11 (rimane in «Mostra altre opzioni»). Dettagli in:
it.CertQuitar=Per rimuovere da questo computer il certificato del menu del clic destro di AventyaPDF, Windows chiederà l'autorizzazione di amministratore.
it.CertNoQuitado=Il certificato di AventyaPDF non è stato rimosso da «Persone attendibili» del computer (l'autorizzazione di amministratore non è stata concessa).%n%nÈ possibile rimuoverlo manualmente: «Gestisci certificati computer» (certlm.msc) › Persone attendibili › Certificati › «Aventya Asesoria Integral SL».
it.MenuFirmar=Firma digitalmente
it.MenuCombinar=Combina in un PDF
it.MenuConvertir=Converti in PDF
it.TipoDocumento=Documento PDF
it.DescripcionApp=Visualizzatore ed editor PDF con firma digitale e OCR
ca.TareaEscritorio=Crea una drecera a l'escriptori
ca.GrupoAccesos=Dreceres:
ca.PreparandoArranque=S'està preparant AventyaPDF per a la primera execució…
ca.AbrirApp=Obre %1
ca.MenuConfianza=Perquè el submenú «AventyaPDF» aparegui al menú del botó dret de Windows 11, Windows ha de confiar en el certificat d'AventyaPDF.%n%nA continuació Windows demanarà permís d'administrador (només aquesta vegada en aquest ordinador).
ca.MenuSinPermiso=No s'ha donat el permís d'administrador.%n%nSense aquest permís, el submenú «AventyaPDF» del botó dret quedarà a «Mostra més opcions». Voleu tornar-lo a demanar?%n%n(També es pot fer més endavant des d'AventyaPDF: Ajuda › Repara el menú contextual de l'Explorador de fitxers.)
ca.MenuFallo=No s'ha pogut afegir el submenú «AventyaPDF» al menú principal de Windows 11 (continua a «Mostra més opcions»). Detall a:
ca.CertQuitar=Per treure d'aquest ordinador el certificat del menú del botó dret d'AventyaPDF, Windows demanarà permís d'administrador.
ca.CertNoQuitado=No s'ha tret el certificat d'AventyaPDF de «Persones de confiança» de l'ordinador (no s'ha donat el permís d'administrador).%n%nEs pot treure manualment: «Administra els certificats de l'ordinador» (certlm.msc) › Persones de confiança › Certificats › «Aventya Asesoria Integral SL».
ca.MenuFirmar=Signa digitalment
ca.MenuCombinar=Combina en un PDF
ca.MenuConvertir=Converteix a PDF
ca.TipoDocumento=Document PDF
ca.DescripcionApp=Visualitzador i editor de PDF amb signatura digital i OCR
gl.TareaEscritorio=Crear un atallo no escritorio
gl.GrupoAccesos=Atallos:
gl.PreparandoArranque=Preparando AventyaPDF para o primeiro inicio…
gl.AbrirApp=Abrir %1
gl.MenuConfianza=Para que o submenú «AventyaPDF» apareza no menú do botón dereito de Windows 11, Windows ten que confiar no certificado de AventyaPDF.%n%nA continuación Windows pedirá permiso de administrador (só esta vez neste equipo).
gl.MenuSinPermiso=Non se deu o permiso de administrador.%n%nSen el, o submenú «AventyaPDF» do botón dereito quedará en «Mostrar máis opcións». Queres volver pedilo?%n%n(Tamén se pode facer máis tarde desde AventyaPDF: Axuda › Reparar o menú contextual do Explorador de ficheiros.)
gl.MenuFallo=Non se puido engadir o submenú «AventyaPDF» ao menú principal de Windows 11 (segue en «Mostrar máis opcións»). Detalle en:
gl.CertQuitar=Para quitar deste equipo o certificado do menú do botón dereito de AventyaPDF, Windows pedirá permiso de administrador.
gl.CertNoQuitado=Non se quitou o certificado de AventyaPDF de «Persoas de confianza» do equipo (non se deu o permiso de administrador).%n%nPódese quitar manualmente: «Xestionar certificados do equipo» (certlm.msc) › Persoas de confianza › Certificados › «Aventya Asesoria Integral SL».
gl.MenuFirmar=Asinar dixitalmente
gl.MenuCombinar=Combinar nun PDF
gl.MenuConvertir=Converter a PDF
gl.TipoDocumento=Documento PDF
gl.DescripcionApp=Visor e editor de PDF con sinatura dixital e OCR
eu.TareaEscritorio=Sortu lasterbide bat mahaigainean
eu.GrupoAccesos=Lasterbideak:
eu.PreparandoArranque=AventyaPDF lehen abiaraztekoa prestatzen…
eu.AbrirApp=Ireki %1
eu.MenuConfianza=«AventyaPDF» azpimenua Windows 11ko eskuineko botoiaren menuan ager dadin, Windows-ek AventyaPDF-ren ziurtagiriaz fidatu behar du.%n%nJarraian, Windows-ek administratzaile-baimena eskatuko du (behin bakarrik ordenagailu honetan).
eu.MenuSinPermiso=Ez da administratzaile-baimena eman.%n%nBaimen hori gabe, eskuineko botoiaren «AventyaPDF» azpimenua «Erakutsi aukera gehiago» barruan geratuko da. Berriro eskatu?%n%n(Geroago ere egin daiteke AventyaPDF-tik: Laguntza › Konpondu Fitxategi-arakatzailearen laster-menua.)
eu.MenuFallo=Ezin izan da «AventyaPDF» azpimenua Windows 11ko menu nagusian gehitu («Erakutsi aukera gehiago» barruan dago oraindik). Xehetasunak hemen:
eu.CertQuitar=AventyaPDF-ren eskuineko botoiaren menuko ziurtagiria ordenagailu honetatik kentzeko, Windows-ek administratzaile-baimena eskatuko du.
eu.CertNoQuitado=Ez da AventyaPDF-ren ziurtagiria kendu ordenagailuko «Pertsona fidagarriak» biltegitik (ez da administratzaile-baimena eman).%n%nEskuz ken daiteke: «Kudeatu ordenagailuaren ziurtagiriak» (certlm.msc) › Pertsona fidagarriak › Ziurtagiriak › «Aventya Asesoria Integral SL».
eu.MenuFirmar=Sinatu digitalki
eu.MenuCombinar=Konbinatu PDF bakarrean
eu.MenuConvertir=Bihurtu PDF
eu.TipoDocumento=PDF dokumentua
eu.DescripcionApp=PDF ikustailea eta editorea, sinadura digitalarekin eta OCRarekin
es.Diapo01Titulo=Varios documentos a la vez
es.Diapo01Texto=Abre varios PDF, imágenes o documentos de Word a la vez (Ctrl+O o arrastrándolos a la ventana). Cada uno va en su pestaña: se reordenan arrastrándolas y Ctrl+Tab pasa de una a otra.
es.Diapo02Titulo=Moverse y buscar
es.Diapo02Texto=Panel lateral (F4) con miniaturas, marcadores, comentarios y firmas. Ctrl+F busca y resalta cada coincidencia; el zoom se ajusta al ancho, a la página o al porcentaje que escribas.
es.Diapo03Titulo=Comentar sobre la página
es.Diapo03Texto=Texto que se escribe directamente donde va a quedar, notas adhesivas, resaltar, subrayar o tachar (sobre el texto o a mano alzada), rectángulos, emojis y borrador. Todo se deshace con Ctrl+Z.
es.Diapo04Titulo=Editar el contenido del PDF
es.Diapo04Texto=Cambia el texto y las imágenes que ya están en el documento: el párrafo se reajusta a su cuadro y las imágenes se mueven, se sustituyen o se borran (tecla C).
es.Diapo05Titulo=Rellenar formularios
es.Diapo05Texto=Los campos se resaltan en azul; se escriben en el propio campo, las casillas se marcan con un clic y los cálculos y validaciones funcionan como en Acrobat.
es.Diapo06Titulo=Organizar páginas
es.Diapo06Texto=Arrastra miniaturas para reordenar y gira, duplica, elimina, inserta, extrae o recorta páginas, todo con deshacer. También divide un documento en partes.
es.Diapo07Titulo=Combinar y convertir
es.Diapo07Texto=Combina en un PDF los documentos abiertos o una selección de PDF, imágenes y Word. Crea un PDF desde imágenes y exporta a Word, a imágenes o a texto.
es.Diapo08Titulo=Desde el Explorador de Windows
es.Diapo08Texto=Con el botón derecho sobre los archivos, el submenú AventyaPDF firma, combina en un PDF o convierte a PDF sin abrir antes la aplicación.
es.Diapo09Titulo=Firma digital PAdES
es.Diapo09Texto=Firma con los certificados de Windows (también DNIe y tarjetas) o con un archivo .pfx, con sellado de tiempo y certificación. El sello visible sale en el idioma de la aplicación.
es.Diapo10Titulo=Firmas verificadas
es.Diapo10Texto=El panel Firmas certificadas comprueba automáticamente cada firma: si el documento se ha alterado y si el certificado es de confianza, según Windows y la lista de confianza de España.
es.Diapo11Titulo=Firma manuscrita
es.Diapo11Texto=Desde la barra de Firma, la plumilla: dibuja tu firma con el ratón, con trazo de estilográfica y el color y grosor que quieras, o carga la imagen de tu firma escaneada.
es.Diapo12Titulo=Reconocimiento de texto (OCR)
es.Diapo12Texto=Convierte los escaneos y las fotos en PDF con texto que se puede buscar y copiar. Endereza la página y corrige la orientación antes de leerla.
es.Diapo13Titulo=Proteger y preparar
es.Diapo13Texto=Contraseña AES-256 y permisos, marca de agua, encabezado y pie, numeración Bates, compresión y exportación a Word, imágenes o texto.
es.Diapo14Titulo=En tu idioma
es.Diapo14Texto=AventyaPDF está en español, inglés, francés, italiano, catalán, gallego y euskera. Se cambia en Ayuda › Idioma, y el manual completo está en Ayuda › Manual de AventyaPDF.
en.Diapo01Titulo=Several documents at once
en.Diapo01Texto=Open several PDFs, images or Word documents at once (Ctrl+O or drag them onto the window). Each one gets its own tab: drag the tabs to reorder them, and Ctrl+Tab switches between them.
en.Diapo02Titulo=Navigate and find
en.Diapo02Texto=Side panel (F4) with thumbnails, bookmarks, comments and signatures. Ctrl+F finds and highlights every match; zoom fits the width, the page or the percentage you type.
en.Diapo03Titulo=Comment on the page
en.Diapo03Texto=Text typed directly where it will appear, sticky notes, highlight, underline or strike through (on the text or freehand), rectangles, emojis and eraser. Everything can be undone with Ctrl+Z.
en.Diapo04Titulo=Edit the PDF content
en.Diapo04Texto=Change the text and images already in the document: the paragraph reflows within its box, and images can be moved, replaced or deleted (C key).
en.Diapo05Titulo=Fill in forms
en.Diapo05Texto=Fields are highlighted in blue; you type directly in the field, tick boxes with a click, and calculations and validations work as in Acrobat.
en.Diapo06Titulo=Organise pages
en.Diapo06Texto=Drag thumbnails to reorder pages, and rotate, duplicate, delete, insert, extract or crop them, all with undo. You can also split a document into parts.
en.Diapo07Titulo=Combine and convert
en.Diapo07Texto=Combine the open documents, or a selection of PDFs, images and Word files, into one PDF. Create a PDF from images and export to Word, images or text.
en.Diapo08Titulo=From File Explorer
en.Diapo08Texto=Right-click files and use the AventyaPDF submenu to sign, combine into one PDF or convert to PDF without opening the app first.
en.Diapo09Titulo=PAdES digital signature
en.Diapo09Texto=Sign with Windows certificates (including the DNIe and smart cards) or a .pfx file, with time stamping and certification. The visible stamp appears in the app's language.
en.Diapo10Titulo=Verified signatures
en.Diapo10Texto=The Digital signatures panel checks each signature automatically: whether the document has been altered and whether the certificate is trusted, according to Windows and the Spanish trusted list.
en.Diapo11Titulo=Handwritten signature
en.Diapo11Texto=From the Signature bar, use the pen nib: draw your signature with the mouse, with a fountain pen stroke in the colour and width you want, or load an image of your scanned signature.
en.Diapo12Titulo=Text recognition (OCR)
en.Diapo12Texto=Turns scans and photos into PDFs with text that can be searched and copied. Straightens the page and corrects its orientation before reading it.
en.Diapo13Titulo=Protect and prepare
en.Diapo13Texto=AES-256 password and permissions, watermark, header and footer, Bates numbering, compression and export to Word, images or text.
en.Diapo14Titulo=In your language
en.Diapo14Texto=AventyaPDF is available in Spanish, English, French, Italian, Catalan, Galician and Basque. Change it in Help › Language; the full manual is in Help › AventyaPDF manual.
fr.Diapo01Titulo=Plusieurs documents à la fois
fr.Diapo01Texto=Ouvrez plusieurs PDF, images ou documents Word à la fois (Ctrl+O ou glisser-déposer). Chacun a son onglet : faites-les glisser pour les réordonner ; Ctrl+Tab passe de l'un à l'autre.
fr.Diapo02Titulo=Naviguer et rechercher
fr.Diapo02Texto=Volet latéral (F4) : miniatures, signets, commentaires et signatures. Ctrl+F recherche et surligne chaque occurrence ; le zoom s'ajuste à la largeur, à la page ou au pourcentage saisi.
fr.Diapo03Titulo=Commenter sur la page
fr.Diapo03Texto=Texte saisi directement à l'endroit où il restera, notes autocollantes, surlignage, soulignement ou texte barré (sur le texte ou à main levée), rectangles, emojis et gomme. Tout s'annule avec Ctrl+Z.
fr.Diapo04Titulo=Modifier le contenu du PDF
fr.Diapo04Texto=Modifiez le texte et les images déjà présents dans le document : le paragraphe se réajuste à son cadre et les images peuvent être déplacées, remplacées ou supprimées (touche C).
fr.Diapo05Titulo=Remplir des formulaires
fr.Diapo05Texto=Les champs sont mis en évidence en bleu ; on écrit directement dans le champ, les cases se cochent d'un clic et les calculs et validations fonctionnent comme dans Acrobat.
fr.Diapo06Titulo=Organiser les pages
fr.Diapo06Texto=Réordonnez les miniatures par glisser-déposer ; faites pivoter, dupliquez, supprimez, insérez, extrayez ou rognez des pages, avec annulation. Fractionnez aussi un document.
fr.Diapo07Titulo=Combiner et convertir
fr.Diapo07Texto=Combinez en un PDF les documents ouverts ou une sélection de PDF, d'images et de Word. Créez un PDF à partir d'images et exportez vers Word, en images ou en texte.
fr.Diapo08Titulo=Depuis l'Explorateur Windows
fr.Diapo08Texto=D'un clic droit sur les fichiers, le sous-menu AventyaPDF signe, combine en un PDF ou convertit en PDF sans ouvrir l'application.
fr.Diapo09Titulo=Signature numérique PAdES
fr.Diapo09Texto=Signez avec les certificats Windows (DNIe et cartes à puce compris) ou un fichier .pfx, avec horodatage et certification. La signature visible apparaît dans la langue de l'application.
fr.Diapo10Titulo=Signatures vérifiées
fr.Diapo10Texto=Le volet Signatures certifiées vérifie automatiquement chaque signature : document modifié ou non, certificat approuvé ou non, selon Windows et la liste de confiance espagnole.
fr.Diapo11Titulo=Signature manuscrite
fr.Diapo11Texto=Depuis la barre Signature, la plume : dessinez votre signature avec la souris, avec un trait de stylo plume de la couleur et de l'épaisseur de votre choix, ou chargez l'image numérisée de votre signature.
fr.Diapo12Titulo=Reconnaissance de texte (OCR)
fr.Diapo12Texto=Convertit les numérisations et les photos en PDF dont le texte peut être recherché et copié. Redresse la page et corrige l'orientation avant de la lire.
fr.Diapo13Titulo=Protéger et préparer
fr.Diapo13Texto=Mot de passe AES-256 et autorisations, filigrane, en-tête et pied de page, numérotation Bates, compression et exportation vers Word, en images ou en texte.
fr.Diapo14Titulo=Dans votre langue
fr.Diapo14Texto=AventyaPDF existe en espagnol, anglais, français, italien, catalan, galicien et basque. La langue se change dans Aide › Langue ; le manuel complet est dans Aide › Manuel d'AventyaPDF.
it.Diapo01Titulo=Più documenti insieme
it.Diapo01Texto=Apri più PDF, immagini o documenti di Word insieme (Ctrl+O o trascinandoli nella finestra). Ognuno ha la sua scheda: trascinale per riordinarle; Ctrl+Tab passa dall'una all'altra.
it.Diapo02Titulo=Spostarsi e cercare
it.Diapo02Texto=Riquadro laterale (F4) con miniature, segnalibri, commenti e firme. Ctrl+F cerca ed evidenzia ogni occorrenza; lo zoom si adatta alla larghezza, alla pagina o alla percentuale scelta.
it.Diapo03Titulo=Commentare sulla pagina
it.Diapo03Texto=Testo scritto direttamente dove deve restare, note adesive, evidenziazione, sottolineatura o barratura (sul testo o a mano libera), rettangoli, emoji e gomma. Tutto si annulla con Ctrl+Z.
it.Diapo04Titulo=Modificare il contenuto del PDF
it.Diapo04Texto=Modifica il testo e le immagini già presenti nel documento: il paragrafo si adatta alla sua casella e le immagini si spostano, si sostituiscono o si eliminano (tasto C).
it.Diapo05Titulo=Compilare moduli
it.Diapo05Texto=I campi sono evidenziati in blu; si scrive direttamente nel campo, le caselle di controllo si selezionano con un clic e i calcoli e le convalide funzionano come in Acrobat.
it.Diapo06Titulo=Organizzare le pagine
it.Diapo06Texto=Trascina le miniature per riordinare e ruota, duplica, elimina, inserisci, estrai o ritaglia pagine, tutto annullabile. Puoi anche dividere un documento in parti.
it.Diapo07Titulo=Combinare e convertire
it.Diapo07Texto=Combina in un PDF i documenti aperti o una selezione di PDF, immagini e Word. Crea un PDF da immagini ed esporta in Word, in immagini o in testo.
it.Diapo08Titulo=Da Esplora file
it.Diapo08Texto=Con il clic destro sui file, il sottomenu AventyaPDF firma, combina in un PDF o converte in PDF senza dover aprire l'applicazione.
it.Diapo09Titulo=Firma digitale PAdES
it.Diapo09Texto=Firma con i certificati di Windows (anche DNIe e smart card) o con un file .pfx, con marcatura temporale e certificazione. Il timbro visibile è nella lingua dell'applicazione.
it.Diapo10Titulo=Firme verificate
it.Diapo10Texto=Il riquadro Firme certificate verifica da sé ogni firma: se il documento è stato alterato e se il certificato è attendibile, secondo Windows e l'elenco di fiducia spagnolo.
it.Diapo11Titulo=Firma autografa
it.Diapo11Texto=Dalla barra Firma, il pennino: disegna la tua firma con il mouse, con tratto stilografico e il colore e lo spessore che preferisci, oppure carica l'immagine della tua firma scansionata.
it.Diapo12Titulo=Riconoscimento del testo (OCR)
it.Diapo12Texto=Converte scansioni e foto in PDF con testo ricercabile e copiabile. Raddrizza la pagina e ne corregge l'orientamento prima di leggerla.
it.Diapo13Titulo=Proteggere e preparare
it.Diapo13Texto=Password AES-256 e autorizzazioni, filigrana, intestazione e piè di pagina, numerazione Bates, compressione ed esportazione in Word, immagini o testo.
it.Diapo14Titulo=Nella tua lingua
it.Diapo14Texto=AventyaPDF è in spagnolo, inglese, francese, italiano, catalano, galiziano e basco. Si cambia in Guida › Lingua; il manuale completo è in Guida › Manuale di AventyaPDF.
ca.Diapo01Titulo=Diversos documents alhora
ca.Diapo01Texto=Obriu diversos PDF, imatges o documents de Word alhora (Ctrl+O o arrossegant-los a la finestra). Cada un va a la seva pestanya: es reordenen arrossegant-les i Ctrl+Tab passa de l'una a l'altra.
ca.Diapo02Titulo=Navegar i cercar
ca.Diapo02Texto=Tauler lateral (F4) amb miniatures, marcadors, comentaris i signatures. Ctrl+F cerca i ressalta cada coincidència; el zoom s'ajusta a l'amplada, a la pàgina o al percentatge que escriviu.
ca.Diapo03Titulo=Comentar sobre la pàgina
ca.Diapo03Texto=Text que s'escriu directament on ha de quedar, notes adhesives, ressaltar, subratllar o ratllar (sobre el text o a mà alçada), rectangles, emojis i esborrador. Tot es desfà amb Ctrl+Z.
ca.Diapo04Titulo=Editar el contingut del PDF
ca.Diapo04Texto=Canvieu el text i les imatges que ja són al document: el paràgraf es reajusta al seu quadre i les imatges es mouen, se substitueixen o s'esborren (tecla C).
ca.Diapo05Titulo=Emplenar formularis
ca.Diapo05Texto=Els camps es ressalten en blau; s'escriu al mateix camp, les caselles es marquen amb un clic i els càlculs i les validacions funcionen com a Acrobat.
ca.Diapo06Titulo=Organitzar pàgines
ca.Diapo06Texto=Arrossegueu miniatures per reordenar i gireu, dupliqueu, suprimiu, inseriu, extraieu o retalleu pàgines, tot amb opció de desfer. També podeu dividir un document en parts.
ca.Diapo07Titulo=Combinar i convertir
ca.Diapo07Texto=Combineu en un PDF els documents oberts o una selecció de PDF, imatges i Word. Creeu un PDF a partir d'imatges i exporteu a Word, a imatges o a text.
ca.Diapo08Titulo=Des de l'Explorador de fitxers
ca.Diapo08Texto=Amb el botó dret sobre els fitxers, el submenú AventyaPDF signa, combina en un PDF o converteix a PDF sense haver d'obrir l'aplicació.
ca.Diapo09Titulo=Signatura digital PAdES
ca.Diapo09Texto=Signeu amb els certificats de Windows (també DNIe i targetes) o amb un fitxer .pfx, amb segellament de temps i certificació. El segell visible surt en l'idioma de l'aplicació.
ca.Diapo10Titulo=Signatures verificades
ca.Diapo10Texto=El tauler Signatures certificades comprova cada signatura automàticament: si el document s'ha alterat i si el certificat és de confiança, segons Windows i la llista de confiança d'Espanya.
ca.Diapo11Titulo=Signatura manuscrita
ca.Diapo11Texto=Des de la barra de Signatura, la ploma: dibuixeu la vostra signatura amb el ratolí, amb traç d'estilogràfica i el color i el gruix que vulgueu, o carregueu la imatge de la vostra signatura escanejada.
ca.Diapo12Titulo=Reconeixement de text (OCR)
ca.Diapo12Texto=Converteix els escanejats i les fotos en PDF amb text que es pot cercar i copiar. Redreça la pàgina i en corregeix l'orientació abans de llegir-la.
ca.Diapo13Titulo=Protegir i preparar
ca.Diapo13Texto=Contrasenya AES-256 i permisos, marca d'aigua, capçalera i peu, numeració Bates, compressió i exportació a Word, imatges o text.
ca.Diapo14Titulo=En el vostre idioma
ca.Diapo14Texto=AventyaPDF està en castellà, anglès, francès, italià, català, gallec i basc. Es canvia a Ajuda › Idioma, i el manual complet és a Ajuda › Manual d'AventyaPDF.
gl.Diapo01Titulo=Varios documentos á vez
gl.Diapo01Texto=Abre varios PDF, imaxes ou documentos de Word á vez (Ctrl+O ou arrastrándoos á xanela). Cada un vai na súa lapela: reordénanse arrastrándoas e Ctrl+Tab pasa dunha a outra.
gl.Diapo02Titulo=Moverse e buscar
gl.Diapo02Texto=Panel lateral (F4) con miniaturas, marcadores, comentarios e sinaturas. Ctrl+F busca e realza cada coincidencia; o zoom axústase á largura, á páxina ou á porcentaxe que escribas.
gl.Diapo03Titulo=Comentar sobre a páxina
gl.Diapo03Texto=Texto que se escribe directamente onde vai quedar, notas adhesivas, realzar, subliñar ou riscar (sobre o texto ou a man alzada), rectángulos, emojis e borrador. Todo se desfai con Ctrl+Z.
gl.Diapo04Titulo=Editar o contido do PDF
gl.Diapo04Texto=Cambia o texto e as imaxes que xa están no documento: o parágrafo reaxústase á súa caixa e as imaxes móvense, substitúense ou bórranse (tecla C).
gl.Diapo05Titulo=Encher formularios
gl.Diapo05Texto=Os campos aparecen realzados en azul; escríbese no propio campo, as caixas de verificación márcanse cun clic e os cálculos e validacións funcionan como en Acrobat.
gl.Diapo06Titulo=Organizar páxinas
gl.Diapo06Texto=Arrastra miniaturas para reordenar e xira, duplica, elimina, insire, extrae ou recorta páxinas, todo con desfacer. Tamén divide un documento en partes.
gl.Diapo07Titulo=Combinar e converter
gl.Diapo07Texto=Combina nun PDF os documentos abertos ou unha selección de PDF, imaxes e Word. Crea un PDF desde imaxes e exporta a Word, a imaxes ou a texto.
gl.Diapo08Titulo=Desde o Explorador de ficheiros
gl.Diapo08Texto=Co botón dereito sobre os ficheiros, o submenú AventyaPDF asina, combina nun PDF ou converte a PDF sen abrir antes a aplicación.
gl.Diapo09Titulo=Sinatura dixital PAdES
gl.Diapo09Texto=Asina cos certificados de Windows (tamén DNIe e tarxetas) ou cun ficheiro .pfx, con selado de tempo e certificación. O selo visible sae no idioma da aplicación.
gl.Diapo10Titulo=Sinaturas verificadas
gl.Diapo10Texto=O panel Sinaturas certificadas comproba automaticamente cada sinatura: se o documento se alterou e se o certificado é de confianza, segundo Windows e a lista de confianza de España.
gl.Diapo11Titulo=Sinatura manuscrita
gl.Diapo11Texto=Desde a barra de Sinatura, a pluma: debuxa a túa sinatura co rato, con trazo de estilográfica e a cor e o grosor que queiras, ou carga a imaxe da túa sinatura dixitalizada.
gl.Diapo12Titulo=Recoñecemento de texto (OCR)
gl.Diapo12Texto=Converte as dixitalizacións e as fotos en PDF con texto que se pode buscar e copiar. Endereita a páxina e corrixe a orientación antes de lela.
gl.Diapo13Titulo=Protexer e preparar
gl.Diapo13Texto=Contrasinal AES-256 e permisos, marca de auga, cabeceira e pé, numeración Bates, compresión e exportación a Word, imaxes ou texto.
gl.Diapo14Titulo=No teu idioma
gl.Diapo14Texto=AventyaPDF está en español, inglés, francés, italiano, catalán, galego e éuscaro. Cámbiase en Axuda › Idioma, e o manual completo está en Axuda › Manual de AventyaPDF.
eu.Diapo01Titulo=Hainbat dokumentu batera
eu.Diapo01Texto=Ireki hainbat PDF, irudi edo Word dokumentu batera (Ctrl+O edo leihora arrastatuta). Bakoitza bere fitxan doa: fitxak arrastatuz ordenatzen dira, eta Ctrl+Tab sakatuta batetik bestera igarotzen da.
eu.Diapo02Titulo=Nabigatu eta bilatu
eu.Diapo02Texto=Alboko panela (F4): koadro txikiak, laster-markak, iruzkinak eta sinadurak. Ctrl+F bilatu eta bat-etortze oro nabarmentzen du; zooma zabalerara, orrialdera edo idatzitako ehunekora doitzen da.
eu.Diapo03Titulo=Iruzkindu orrialdean
eu.Diapo03Texto=Testua geratuko den lekuan bertan idazten da; ohar itsaskorrak; nabarmendu, azpimarratu edo marratu (testuaren gainean edo eskuz); laukizuzenak, emojiak eta borragoma. Dena desegin daiteke Ctrl+Z bidez.
eu.Diapo04Titulo=Editatu PDFaren edukia
eu.Diapo04Texto=Aldatu dokumentuan dauden testua eta irudiak: paragrafoa bere koadrora doitzen da berriro, eta irudiak mugitu, ordeztu edo ezabatu egin daitezke (C tekla).
eu.Diapo05Titulo=Bete inprimakiak
eu.Diapo05Texto=Eremuak urdinez nabarmentzen dira; eremuan bertan idazten da, kontrol-laukiak klik batekin markatzen dira, eta kalkuluek eta baliozkotzeek Acrobat-en bezala funtzionatzen dute.
eu.Diapo06Titulo=Antolatu orrialdeak
eu.Diapo06Texto=Arrastratu koadro txikiak ordenatzeko, eta biratu, bikoiztu, ezabatu, txertatu, atera edo moztu orrialdeak, dena desegin daitekeela. Dokumentuak zatitan ere banatzen ditu.
eu.Diapo07Titulo=Konbinatu eta bihurtu
eu.Diapo07Texto=Konbinatu PDF bakarrean dokumentu irekiak edo hautatutako PDF, irudi eta Word fitxategiak. Sortu PDFa irudietatik, eta esportatu Word-era, irudietara edo testura.
eu.Diapo08Titulo=Fitxategi-arakatzailetik
eu.Diapo08Texto=Fitxategien gainean eskuineko botoiarekin, AventyaPDF azpimenuak sinatu, PDF bakarrean konbinatu edo PDF bihurtzen ditu, aplikazioa ireki gabe.
eu.Diapo09Titulo=PAdES sinadura digitala
eu.Diapo09Texto=Sinatu Windows-eko ziurtagiriekin (DNIe eta txartelak barne) edo .pfx fitxategi batekin, denbora-zigilatzearekin eta ziurtapenarekin. Zigilu ikusgaia aplikazioaren hizkuntzan ateratzen da.
eu.Diapo10Titulo=Egiaztatutako sinadurak
eu.Diapo10Texto=Ziurtagiridun sinadurak panelak berak egiaztatzen ditu sinadurak: dokumentua aldatu den eta ziurtagiria fidagarria den, Windows-en eta Espainiako konfiantza-zerrendaren arabera.
eu.Diapo11Titulo=Eskuzko sinadura
eu.Diapo11Texto=Sinadura-barratik, lumarekin: marraztu zure sinadura saguarekin, luma estilografikoaren trazuarekin eta nahi duzun kolore eta lodierarekin, edo kargatu zure sinadura eskaneatuaren irudia.
eu.Diapo12Titulo=Testu-ezagutza (OCR)
eu.Diapo12Texto=Bihurtu eskaneatutako dokumentuak eta argazkiak testu bilagarri eta kopiagarria duten PDF. Orrialdea zuzendu eta orientazioa konpontzen du irakurri aurretik.
eu.Diapo13Titulo=Babestu eta prestatu
eu.Diapo13Texto=AES-256 pasahitza eta baimenak, ur-marka, goiburua eta orri-oina, Bates zenbakitzea, konpresioa, eta esportazioa Word-era, irudietara edo testura.
eu.Diapo14Titulo=Zure hizkuntzan
eu.Diapo14Texto=AventyaPDF gaztelaniaz, ingelesez, frantsesez, italieraz, katalanez, galizieraz eta euskaraz dago. Aldatzeko: Laguntza › Hizkuntza. Eskuliburu osoa: Laguntza › AventyaPDF-ren eskuliburua.
